// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
#include "stm32h7xx_hal.h"

// Custom time function for Mongoose - returns milliseconds since boot
uint64_t mg_millis(void) {
  return HAL_GetTick();
}

// Custom random function for Mongoose - fills buffer with random bytes
bool mg_random(void *buf, size_t len) {
  extern RNG_HandleTypeDef hrng;
  uint8_t *p = (uint8_t *)buf;

  for (size_t i = 0; i < len; i += sizeof(uint32_t)) {
    uint32_t random_number = 0;
    if (HAL_RNG_GenerateRandomNumber(&hrng, &random_number) != HAL_OK) {
      return false;
    }
    size_t remaining = len - i;
    size_t to_copy = (remaining < sizeof(uint32_t)) ? remaining : sizeof(uint32_t);
    memcpy(&p[i], &random_number, to_copy);
  }
  return true;
}

static struct leds s_leds = {false, false, false};
void glue_get_leds(struct leds *data) {
  *data = s_leds;  // Sync with your device
}
void glue_set_leds(struct leds *data) {
  s_leds = *data; // Sync with your device
}

void *glue_ota_begin_firmware_update(char *file_name, size_t total_size) {
  bool ok = mg_ota_begin(total_size);
  MG_DEBUG(("%s size %lu, ok: %d", file_name, total_size, ok));
  return ok ? (void *) 1 : NULL;
}
bool glue_ota_end_firmware_update(void *context) {
  mg_timer_add(&g_mgr, 500, 0, (void (*)(void *)) (void *) mg_ota_end, context);
  return true;
}
bool glue_ota_write_firmware_update(void *context, void *buf, size_t len) {
  MG_DEBUG(("ctx: %p %p/%lu", context, buf, len));
  return mg_ota_write(buf, len);
}
